version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: house_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: house_price_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: house_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: house_price_db
    ports:
      - "8000:8000"
    command: >
      sh -c "
      uv sync &&
      uv run python create_database.py &&
      uv run alembic upgrade head &&
      uv run python -m app.train &&
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  ai_service:
    build: ./ai_service
    container_name: house_ai_service
    restart: always
    env_file:
      - ./ai_service/.env
    ports:
      - "8080:8080"
    command: >
      sh -c "
      uv sync &&
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8080
      "

  frontend:
    build: ./frontend
    container_name: house_frontend
    restart: always
    ports:
      - "80:80"

volumes:
  mysql_data:
